version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the stdLibSchema directory
    directory: "/stdLibSchema"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Add assignees
    assignees:
      - "Philoraptor"
    # Add labels
    labels:
      - "dependencies"
      - "npm"
    # Group updates
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
      dev-dependencies:
        patterns:
          - "*"
        dependency-type: "development"
        exclude-patterns:
          - "@angular/*"
          - "@angular-devkit/*"
    # Ignore specific dependencies or versions
    ignore:
      # Don't update major versions automatically
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular-devkit/schematics"
        update-types: ["version-update:semver-major"]
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "Philoraptor"